<?php
return array (
  'dplayer' => 
  array (
    'status' => '1',
    'from' => 'dplayer',
    'show' => 'DPlayer-H5播放器',
    'des' => 'dplayer.js.org',
    'target' => '_self',
    'ps' => '0',
    'parse' => '',
    'sort' => '908',
    'tip' => '无需安装任何插件',
    'id' => 'dplayer',
  ),
  'videojs' => 
  array (
    'status' => '1',
    'sort' => '907',
    'from' => 'videojs',
    'show' => 'videojs-H5播放器',
    'des' => 'videojs.com',
    'parse' => '',
    'ps' => '0',
    'tip' => '无需安装任何插件',
    'id' => 'videojs',
  ),
  'iva' => 
  array (
    'status' => '1',
    'from' => 'iva',
    'show' => 'iva-H5播放器',
    'des' => 'videojj.com',
    'target' => '_self',
    'ps' => '0',
    'parse' => '',
    'sort' => '906',
    'tip' => '无需安装任何插件',
    'id' => 'iva',
  ),
  'iframe' => 
  array (
    'status' => '1',
    'from' => 'iframe',
    'show' => 'iframe外链数据',
    'des' => 'iframe外链数据',
    'ps' => '0',
    'parse' => '',
    'sort' => '905',
    'tip' => '无需安装任何插件',
    'id' => 'iframe',
  ),
  'link' => 
  array (
    'status' => '1',
    'sort' => '904',
    'from' => 'link',
    'show' => '外链数据',
    'des' => '外部网站播放链接',
    'ps' => '0',
    'parse' => '',
    'tip' => '无需安装任何插件',
    'id' => 'link',
  ),
  'swf' => 
  array (
    'status' => '1',
    'sort' => '903',
    'from' => 'swf',
    'show' => 'Flash文件',
    'des' => 'swf',
    'parse' => '',
    'ps' => '0',
    'tip' => '无需安装任何插件',
    'id' => 'swf',
  ),
  'flv' => 
  array (
    'status' => '1',
    'from' => 'flv',
    'show' => 'Flv文件',
    'des' => 'flv',
    'target' => '_self',
    'ps' => '0',
    'parse' => '',
    'sort' => '902',
    'tip' => '无需安装任何插件	',
    'id' => 'flv',
  ),
  'tkm3u8' => 
  array (
    'status' => '1',
    'from' => 'tkm3u8',
    'show' => '天空资源',
    'des' => '',
    'target' => '_self',
    'ps' => '0',
    'parse' => '',
    'sort' => '50',
    'tip' => '',
  ),
  'sdm3u8' => 
  array (
    'status' => '1',
    'from' => 'sdm3u8',
    'show' => '闪电资源',
    'des' => '',
    'target' => '_self',
    'ps' => '0',
    'parse' => '',
    'sort' => '40',
    'tip' => '',
    'id' => 'sdm3u8',
  ),
  'ukm3u8' => 
  array (
    'status' => '1',
    'from' => 'ukm3u8',
    'show' => 'U酷资源',
    'des' => '',
    'target' => '_self',
    'ps' => '0',
    'parse' => '',
    'sort' => '30',
    'tip' => '',
  ),
  'wjm3u8' => 
  array (
    'status' => '1',
    'from' => 'wjm3u8',
    'show' => '无尽资源',
    'des' => '',
    'target' => '_self',
    'ps' => '0',
    'parse' => '',
    'sort' => '20',
    'tip' => '',
  ),
  'hnm3u8' => 
  array (
    'status' => '1',
    'from' => 'hnm3u8',
    'show' => '红牛资源',
    'des' => '',
    'target' => '_self',
    'ps' => '0',
    'parse' => '',
    'sort' => '10',
    'tip' => '',
    'id' => 'hnm3u8',
  ),
);